rpm,init: Move the pg user creaction and moodle db initialisation to init script
It turns out that we cannot initialise the DB schema
and related things from %post - as it'll often run
in anaconda-driven install, upgrade. So we put a flag
that /etc/init.d/moodle script will check and attempt
the install/upgrade process.

diff --git a/rpm/moodle.init b/rpm/moodle.init
--- a/rpm/moodle.init
+++ b/rpm/moodle.init
@@ -5,7 +5,7 @@
 # Author:       Ignacio Vazquez-Abrams <ivazquez@ivazquez.net>
 # Adapted from the yum initscript by Seth Vidal
 #
-# chkconfig: - 50 01
+# chkconfig: 345 50 01
 #
 # description:  Enable the Moodle cron job
 #
@@ -31,6 +31,31 @@ lockfile=/var/lock/subsys/moodle
 RETVAL=0
 
 start() {
+	
+        if [ -e /etc/moodle/needsupgrade ]; then
+                echo "Moodle installation or upgrade required..."
+                # Attempt to create an 'apache' user in PostgreSQL
+                su  -c 'createuser -SRD apache' postgres || echo 'Could not create apache user (exists already?)'
+                # attempt to create a database
+                su -c 'createdb -O apache -E utf8 moodle-xs' postgres || echo 'Could not create moodle-xs DB (exists already?)'
+		# Install/upgrade moodle DB schema
+		( sudo -u apache /usr/bin/php /var/www/moodle/web/admin/cliupgrade.php \
+		    --agreelicense=yes --confirmrelease=yes \
+		    --sitefullname='School Server' \
+		    --siteshortname='XS' \
+		    --sitesummary='Put the name of your school here' \
+		    --adminfirstname=Admin --adminlastname=OLPC \
+		    --adminusername=admin --adminpassword=`cat /etc/moodle/adminpw` \
+		    --adminemail=admin@localhost \
+		    --verbose=0 --interactivelevel=0 2>&1 ) >> /var/log/moodle-instupg.log 
+		if [ $? = 0 ]; then
+		    success
+		    rm -f /etc/moodle/needsupgrade
+		else
+		    failure
+		    exit 1
+		fi
+	fi
 	echo -n $"Enabling Moodle access and cron job: "
 	touch "$lockfile" && success || failure
 	RETVAL=$?
