Configuration: provide a suitable moodle config, and auto-create DB.

diff --git a/rpm/moodle-xs.spec.in b/rpm/moodle-xs.spec.in
--- a/rpm/moodle-xs.spec.in
+++ b/rpm/moodle-xs.spec.in
@@ -23,8 +23,10 @@ Requires:       perl(Encode) perl(Text::Aspell) perl(HTML::Parser) php
 Requires:       perl(HTML::Entities) perl(CGI)
 Requires:       mimetex
 Requires(post): /sbin/chkconfig
+Requires(post): pwgen
 Requires(preun): /sbin/chkconfig
 Requires(preun): /sbin/service
+
 
 Conflicts:      moodle
 
@@ -63,6 +65,7 @@ rm -rf $RPM_BUILD_ROOT
 mkdir -p $RPM_BUILD_ROOT%{moodlewebdir}
 mkdir -p $RPM_BUILD_ROOT%{moodledatadir}
 mkdir -p $RPM_BUILD_ROOT%{_var}/log/moodle
+mkdir -p $RPM_BUILD_ROOT%{_sysconfdir}/moodle
 cp -a * $RPM_BUILD_ROOT%{moodlewebdir}
 rm $RPM_BUILD_ROOT%{moodlewebdir}/README*
 rm -fr $RPM_BUILD_ROOT%{moodlewebdir}/install
@@ -82,6 +85,26 @@ rm -rf $RPM_BUILD_ROOT
 
 %post
 /sbin/chkconfig --add moodle
+# Attempt to create an 'apache' user in PostgreSQL
+su  -c 'createuser -SRD apache' postgres || echo 'Could not create apache user (exists already?)'
+# attempt to create a database
+su -c 'createdb -O apache -E utf8 moodle-xs' postgres || echo 'Could not create moodle-xs DB (exists already?)'
+# create a safe password
+if [ ! -e /etc/moodle/adminpw -o -z /etc/moodle/adminpw ]; then
+   pwgen -1 -B 12 > /etc/moodle/adminpw
+   chmod 600 /etc/moodle/adminpw
+fi
+
+sudo -u apache /usr/bin/php /var/www/moodle/web/admin/cliupgrade.php \
+ --agreelicense=yes --confirmrelease=yes \
+ --sitefullname='School Server' \
+ --siteshortname='XS' \
+ --sitesummary='Put the name of your school here' \
+ --adminfirstname=Admin --adminlastname=OLPC \
+ --adminusername=admin --adminpassword=`cat /etc/moodle/adminpw` \
+ --adminemail=admin@localhost \
+ --verbose=0 --interactivelevel=0 
+
 
 %preun
 if [ $1 = 0 ]; then
@@ -94,6 +117,7 @@ fi
 %doc README*
 %dir %{_var}/www/moodle
 %dir %{moodlewebdir}
+%dir %{_sysconfdir}/moodle
 %config(noreplace) %{moodlewebdir}/config.php
 %config(noreplace) %{_sysconfdir}/logrotate.d/moodle
 %attr(-,apache,apache) %{moodledatadir}
